# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\tsentiment\"0\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\".\n\x0eSentimentScore\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"\xc3\x01\n\x0f\x41nalyzeResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x15\n\rsentiment_key\x18\x02 \x01(\t\x12\x17\n\x0fsentiment_value\x18\x03 \x01(\x01\x12>\n\nsentiments\x18\x04 \x03(\x0b\x32*.sentiment.AnalyzeResponse.SentimentsEntry\x1a\x31\n\x0fSentimentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"?\n\x13\x42\x61tchAnalyzeRequest\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.sentiment.AnalyzeRequest\"C\n\x14\x42\x61tchAnalyzeResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.sentiment.AnalyzeResponse2\xa5\x01\n\x10SentimentService\x12@\n\x07\x41nalyze\x12\x19.sentiment.AnalyzeRequest\x1a\x1a.sentiment.AnalyzeResponse\x12O\n\x0c\x42\x61tchAnalyze\x12\x1e.sentiment.BatchAnalyzeRequest\x1a\x1f.sentiment.BatchAnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZERESPONSE_SENTIMENTSENTRY']._loaded_options = None
  _globals['_ANALYZERESPONSE_SENTIMENTSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUEST']._serialized_start=30
  _globals['_ANALYZEREQUEST']._serialized_end=78
  _globals['_SENTIMENTSCORE']._serialized_start=80
  _globals['_SENTIMENTSCORE']._serialized_end=126
  _globals['_ANALYZERESPONSE']._serialized_start=129
  _globals['_ANALYZERESPONSE']._serialized_end=324
  _globals['_ANALYZERESPONSE_SENTIMENTSENTRY']._serialized_start=275
  _globals['_ANALYZERESPONSE_SENTIMENTSENTRY']._serialized_end=324
  _globals['_BATCHANALYZEREQUEST']._serialized_start=326
  _globals['_BATCHANALYZEREQUEST']._serialized_end=389
  _globals['_BATCHANALYZERESPONSE']._serialized_start=391
  _globals['_BATCHANALYZERESPONSE']._serialized_end=458
  _globals['_SENTIMENTSERVICE']._serialized_start=461
  _globals['_SENTIMENTSERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
